# Generated by Django 5.0.6 on 2024-07-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_session_id_payment_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Время последнего посещения'),
        ),
    ]
