# Generated by Django 5.0.6 on 2024-07-10 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 10, 17, 32, 42, 242252, tzinfo=datetime.timezone.utc), null=True, verbose_name='Время последнего посещения'),
        ),
    ]
